name: Update tide data
on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 3 1 11 *'

jobs:
  update:
    name: update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/scripts/requirements.txt

      - name: Run script
        run: |
          python src/scripts/create_data.py

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3.4.1
        with:
          title: Update tide data.
          labels: Auto PR